In [1]:
import pandas as pd
import numpy as np
import sklearn as sk
import seaborn as sns
import matplotlib.pyplot as plt
from google.colab import drive
import math

In [2]:
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [3]:
df = pd.read_csv('/content/gdrive/MyDrive/Teaching Notebooks/Data/vgsales.csv')

In [4]:
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [5]:
list1 = [1, 2, 3, 4, 'k']

dict1 = {}

tupe1 = (1, 2, 3, 'k')

In [6]:
data = np.array(['g', 'e', 'e', 'k', 's'])
data2 = np.array([1, 2, 3, 4, 5])
# Notebooks will auto print the last line if it is just a variable
print(type(data))
data2

<class 'numpy.ndarray'>

array([1, 2, 3, 4, 5])

In [7]:
ser = pd.Series(data)
ser

# this is one line

"""
This will
do as many
lines as
you want
"""

'\nThis will\ndo as many\nlines as\nyou want\n'

In [8]:
data_frame = pd.DataFrame(ser)
data_frame

   0
0  g
1  e
2  e
3  k
4  s

In [9]:
### PYTHON QUIRKS ###
# the \ is a line break, you cannot have anything after it
new_list = [1, 2, \
            3, 4]
# The below new list wont run because there is a space
"""new_list = [1, 2, \ 
            3, 4]"""

# You can add strings together
new_str = "Hello" + " " + "World"
print(new_str)

int1 = 6
string1 = f"""The number of the day is {int1}!!!"""
string2 = """The number of the day is {} 4head.""".format(int1)
string3 = f"testing number {int1} and int1"
#string4 = "testing number {int1} and {}".format(int1)
print(string1)
print(string2)
#print(string3)

Hello World
The number of the day is 6!!!
The number of the day is 6 4head.

In [10]:
def func():
  var1 = 12
  var1 = 'k'

for i in range(3):
  i += 1


tup1 = (1, 2, 3)
tup1 = ('k', 'boomer')
tup1

list1 = ['okay', 'boomer']
# You can loop through objects implicitly
for item in list1:
  print(item)

str1 = "test"

for stringloop in str1:
  print(stringloop)

if tup1[0] == 1:
  print(list1[1])
elif tup1[1] == 3:
  print(list1[0])
else:
  print('None')

l1 = lambda x: x + 3

print(l1(10))

okay
boomer
t
e
s
t
None
13

Part 2:

In [11]:
df.columns # gives columns
df.dtypes # gives the type of each column

Rank              int64
Name             object
Platform         object
Year            float64
Genre            object
Publisher        object
NA_Sales        float64
EU_Sales        float64
JP_Sales        float64
Other_Sales     float64
Global_Sales    float64
dtype: object

In [12]:
df.index

RangeIndex(start=0, stop=16598, step=1)

In [13]:
df2 = df.set_index(['Genre', 'Year'])
df2.head()

,,Rank,Name,Platform,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
Genre,Year,,,,,,,,,
Sports,2006.0,1,Wii Sports,Wii,Nintendo,41.49,29.02,3.77,8.46,82.74
Platform,1985.0,2,Super Mario Bros.,NES,Nintendo,29.08,3.58,6.81,0.77,40.24
Racing,2008.0,3,Mario Kart Wii,Wii,Nintendo,15.85,12.88,3.79,3.31,35.82
Sports,2009.0,4,Wii Sports Resort,Wii,Nintendo,15.75,11.01,3.28,2.96,33.00
Role-Playing,1996.0,5,Pokemon Red/Pokemon Blue,GB,Nintendo,11.27,8.89,10.22,1.00,31.37

In [14]:
# When referencing columns, or just subsets of columns you need to use []

df['Year']

# If you want multiple you need a list of strings 
df[['Year', 'Platform', 'Publisher']]

         Year Platform   Publisher
0      2006.0      Wii    Nintendo
1      1985.0      NES    Nintendo
2      2008.0      Wii    Nintendo
3      2009.0      Wii    Nintendo
4      1996.0       GB    Nintendo
...       ...      ...         ...
16593  2002.0      GBA       Kemco
16594  2003.0       GC  Infogrames
16595  2008.0      PS2  Activision
16596  2010.0       DS    7G//AMES
16597  2003.0      GBA     Wanadoo

[16598 rows x 3 columns]

In [15]:
# Lets say we want just 2006

# in sql it would be like select(*) FROM perfect_table_that_definately_exists where Year = 2006
df[df['Year'] == 2006]
#df['version'] += 1
df1 = df[((df['Platform'] == 'PSP') ^ (df['Year'] == 2006))
  & (df['NA_Sales']+df['EU_Sales']+df['JP_Sales'] >= 5)]
df1

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
6,7,New Super Mario Bros.,DS,2006.0,Platform,Nintendo,11.38,9.23,6.50,2.90,30.01
7,8,Wii Play,Wii,2006.0,Misc,Nintendo,14.03,9.20,2.93,2.85,29.02
20,21,Pokemon Diamond/Pokemon Pearl,DS,2006.0,Role-Playing,Nintendo,6.42,4.52,6.04,1.37,18.36
90,91,Grand Theft Auto: Liberty City Stories,PSP,2005.0,Action,Take-Two Interactive,2.90,2.83,0.24,1.75,7.72
100,101,The Legend of Zelda: Twilight Princess,Wii,2006.0,Action,Nintendo,3.83,2.19,0.60,0.70,7.31
141,142,Gears of War,X360,2006.0,Shooter,Microsoft Game Studios,3.54,1.90,0.07,0.60,6.11
153,154,Cooking Mama,DS,2006.0,Simulation,505 Games,3.13,1.94,0.07,0.58,5.72
161,162,Monster Hunter Freedom Unite,PSP,2008.0,Role-Playing,Capcom,0.47,0.57,4.13,0.34,5.50

In [16]:
df2.reset_index().head()

,Genre,Year,Rank,Name,Platform,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,Sports,2006.0,1,Wii Sports,Wii,Nintendo,41.49,29.02,3.77,8.46,82.74
1,Platform,1985.0,2,Super Mario Bros.,NES,Nintendo,29.08,3.58,6.81,0.77,40.24
2,Racing,2008.0,3,Mario Kart Wii,Wii,Nintendo,15.85,12.88,3.79,3.31,35.82
3,Sports,2009.0,4,Wii Sports Resort,Wii,Nintendo,15.75,11.01,3.28,2.96,33.00
4,Role-Playing,1996.0,5,Pokemon Red/Pokemon Blue,GB,Nintendo,11.27,8.89,10.22,1.00,31.37

In [17]:
df['NA_Sales'].mean()

0.26466742981082064

In [18]:
df.columns

Index(['Rank', 'Name', 'Platform', 'Year', 'Genre', 'Publisher', 'NA_Sales',
       'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales'],
      dtype='object')

In [19]:
df[['Year', 'Publisher', 'NA_Sales','EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales']].groupby(by=['Year', 'Publisher'], as_index = False).mean()

,Year,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1980.0,Activision,0.564000,0.036000,0.000,0.006000,0.604000
1,1980.0,Atari,1.942500,0.122500,0.000,0.022500,2.090000
2,1981.0,20th Century Fox Video Games,0.423333,0.023333,0.000,0.003333,0.450000
3,1981.0,Activision,1.325000,0.076667,0.000,0.013333,1.416667
4,1981.0,Atari,0.715455,0.042727,0.000,0.007273,0.768182
...,...,...,...,...,...,...,...
2316,2016.0,Yeti,0.000000,0.000000,0.020,0.000000,0.020000
2317,2016.0,dramatic create,0.000000,0.000000,0.015,0.000000,0.015000
2318,2017.0,Idea Factory,0.000000,0.000000,0.010,0.000000,0.010000
2319,2017.0,Sega,0.000000,0.000000,0.020,0.000000,0.020000
2320,2020.0,Ubisoft,0.270000,0.000000,0.000,0.020000,0.290000

In [20]:
agg_type = {'NA_Sales':'mean', 'Global_Sales':'max'}
df[['Year', 'Publisher', 'NA_Sales', 'Global_Sales']].groupby(by=['Year', 'Publisher'], as_index = False).agg(agg_type).rename(columns = {'NA_Sales':'na_mean', 'Global_Sales':'global_max'})

        Year                     Publisher   na_mean  global_max
0     1980.0                    Activision  0.564000        1.15
1     1980.0                         Atari  1.942500        4.31
2     1981.0  20th Century Fox Video Games  0.423333        0.79
3     1981.0                    Activision  1.325000        4.50
4     1981.0                         Atari  0.715455        1.97
...      ...                           ...       ...         ...
2316  2016.0                          Yeti  0.000000        0.02
2317  2016.0               dramatic create  0.000000        0.02
2318  2017.0                  Idea Factory  0.000000        0.01
2319  2017.0                          Sega  0.000000        0.03
2320  2020.0                       Ubisoft  0.270000        0.29

[2321 rows x 4 columns]

In [21]:
df.columns = df.columns.str.lower()
#df = df.rename(columns = {'year':'release_year'})
df

,rank,name,platform,year,genre,publisher,na_sales,eu_sales,jp_sales,other_sales,global_sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [22]:
dfmean = df[['year', 'publisher', 'na_sales', 'global_sales']].groupby(by=['year', 'publisher'], as_index = False).mean().rename(columns = {'na_sales':'na_mean', 'global_sales':'global_mean'})
dfmax = df[['year', 'publisher', 'na_sales', 'global_sales']].groupby(by=['year', 'publisher'], as_index = False).max().rename(columns = {'na_sales':'na_max', 'global_sales':'global_max'})
pd.merge(dfmean, dfmax, how = 'inner',on = ['year', 'publisher'])

,year,publisher,na_mean,global_mean,na_max,global_max
0,1980.0,Activision,0.564000,0.604000,1.07,1.15
1,1980.0,Atari,1.942500,2.090000,4.00,4.31
2,1981.0,20th Century Fox Video Games,0.423333,0.450000,0.74,0.79
3,1981.0,Activision,1.325000,1.416667,4.21,4.50
4,1981.0,Atari,0.715455,0.768182,1.84,1.97
...,...,...,...,...,...,...
2316,2016.0,Yeti,0.000000,0.020000,0.00,0.02
2317,2016.0,dramatic create,0.000000,0.015000,0.00,0.02
2318,2017.0,Idea Factory,0.000000,0.010000,0.00,0.01
2319,2017.0,Sega,0.000000,0.020000,0.00,0.03
2320,2020.0,Ubisoft,0.270000,0.290000,0.27,0.29

In [23]:
dfmean = df[['year', 'publisher', 'na_sales', 'global_sales']].groupby(by=['year', 'publisher'], as_index = False).mean().rename(columns = {'na_sales':'na_mean', 'global_sales':'global_mean'})
dfmax = df[['year', 'publisher', 'na_sales', 'global_sales']].groupby(by=['year', 'publisher'], as_index = False).max().rename(columns = {'year':'years', 'na_sales':'na_max', 'global_sales':'global_max'})
pd.merge(dfmean, dfmax, how = 'inner', left_on = ['year', 'publisher'], right_on = ['years', 'publisher'])

,year,publisher,na_mean,global_mean,years,na_max,global_max
0,1980.0,Activision,0.564000,0.604000,1980.0,1.07,1.15
1,1980.0,Atari,1.942500,2.090000,1980.0,4.00,4.31
2,1981.0,20th Century Fox Video Games,0.423333,0.450000,1981.0,0.74,0.79
3,1981.0,Activision,1.325000,1.416667,1981.0,4.21,4.50
4,1981.0,Atari,0.715455,0.768182,1981.0,1.84,1.97
...,...,...,...,...,...,...,...
2316,2016.0,Yeti,0.000000,0.020000,2016.0,0.00,0.02
2317,2016.0,dramatic create,0.000000,0.015000,2016.0,0.00,0.02
2318,2017.0,Idea Factory,0.000000,0.010000,2017.0,0.00,0.01
2319,2017.0,Sega,0.000000,0.020000,2017.0,0.00,0.03
2320,2020.0,Ubisoft,0.270000,0.290000,2020.0,0.27,0.29

In [24]:
#df.to_csv(filename)
df['publisher_lower'] = df['publisher'].str.lower()
df['publisher_count'] = df['publisher'].str.len()
df['publisher_whitespace'] = np.where(df['genre'] == 'Platform', ' ' + df['publisher'], df['publisher'])
df['publisher_whitespace'] = df['publisher_whitespace'].str.strip()
df['whitespace_count'] = df['publisher_whitespace'].str.len()
df['publisher_lower'] = df['publisher_lower'].str.replace('//', '')
df

,rank,name,platform,year,genre,publisher,na_sales,eu_sales,jp_sales,other_sales,global_sales,publisher_lower,publisher_count,publisher_whitespace,whitespace_count
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,nintendo,8.0,Nintendo,8.0
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,nintendo,8.0,Nintendo,8.0
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,nintendo,8.0,Nintendo,8.0
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,nintendo,8.0,Nintendo,8.0
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,nintendo,8.0,Nintendo,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01,kemco,5.0,Kemco,5.0
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01,infogrames,10.0,Infogrames,10.0
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01,activision,10.0,Activision,10.0
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01,7games,8.0,7G//AMES,8.0
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,wanadoo,7.0,Wanadoo,7.0

In [25]:
df[['split', 'split2']] = df['name'].str.split(pat = ' ', n = 1, expand = True)
df = df.rename(columns = {'year':'release_year'})
df

,rank,name,platform,release_year,genre,publisher,na_sales,eu_sales,jp_sales,other_sales,global_sales,publisher_lower,publisher_count,publisher_whitespace,whitespace_count,split,split2
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,nintendo,8.0,Nintendo,8.0,Wii,Sports
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,nintendo,8.0,Nintendo,8.0,Super,Mario Bros.
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,nintendo,8.0,Nintendo,8.0,Mario,Kart Wii
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,nintendo,8.0,Nintendo,8.0,Wii,Sports Resort
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,nintendo,8.0,Nintendo,8.0,Pokemon,Red/Pokemon Blue
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01,kemco,5.0,Kemco,5.0,Woody,Woodpecker in Crazy Castle 5
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01,infogrames,10.0,Infogrames,10.0,Men,in Black II: Alien Escape
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01,activision,10.0,Activision,10.0,SCORE,International Baja 1000: The Official Game
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01,7games,8.0,7G//AMES,8.0,Know,How 2
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,wanadoo,7.0,Wanadoo,7.0,Spirits,& Spells

In [26]:
#melt & pivot dat ass
#solve by merging so no platform x or y, and the index starts reset
#solve by filtering publishers <= 250 using value_counts and filtering df with list no group bys or joins
df_filtered = df[['publisher', 'platform']].groupby(by = 'publisher', as_index = False).count()
df_filtered = df_filtered[df_filtered['platform'] >= 250]
df_filtered = df_filtered['publisher']
#df_filtered.reset_index()
df_filtered = pd.merge(left = df[['publisher', 'platform', 'global_sales']], right = df_filtered, on = 'publisher')
df_filtered = df_filtered[['publisher', 'platform', 'global_sales']].groupby(by = ['publisher', 'platform']).sum()
df_filtered
df_filtered.reset_index()
#df_filtered = df[['platform', 'global_sales', 'publisher']].where(df['publisher'].count() > 50) #publishers that have made more than 50 games
#df_pivot = df[['']]

      publisher platform  global_sales
0    Activision     2600         19.42
1    Activision      3DS          4.66
2    Activision       DC          0.10
3    Activision       DS         42.11
4    Activision       GB          1.33
..          ...      ...           ...
221     Ubisoft      Wii         92.21
222     Ubisoft     WiiU          5.78
223     Ubisoft     X360         81.59
224     Ubisoft       XB         23.36
225     Ubisoft     XOne         17.91

[226 rows x 3 columns]

In [27]:
df_filtered.reset_index().pivot(columns = 'publisher', values = 'global_sales', index = 'platform').fillna(0)

publisher,Activision,Atari,Capcom,Electronic Arts,Konami Digital Entertainment,Namco Bandai Games,Nintendo,Sega,Sony Computer Entertainment,THQ,Take-Two Interactive,Tecmo Koei,Ubisoft
platform,,,,,,,,,,,,,
2600,19.42,50.09,0.00,0.00,0.00,0.00,0.00,0.40,0.00,0.00,0.00,0.00,0.00
3DO,0.00,0.00,0.00,0.00,0.06,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
3DS,4.66,0.05,10.68,2.72,2.31,11.37,156.45,5.84,0.00,0.52,0.15,0.67,4.31
DC,0.10,0.00,0.27,0.00,0.06,0.38,0.00,12.52,0.00,0.00,0.00,0.00,0.20
DS,42.11,7.13,9.45,32.95,13.52,16.06,349.75,29.54,0.00,36.68,9.46,1.94,59.71
GB,1.33,0.00,1.57,1.73,6.48,3.23,230.09,0.00,0.00,0.00,0.00,0.00,0.12
GBA,15.30,12.90,6.65,14.31,19.20,5.82,112.00,5.31,0.00,47.83,0.35,0.01,9.84
GC,13.35,6.42,6.77,27.96,3.07,4.74,79.15,9.53,0.00,13.97,0.39,0.09,4.40
GEN,0.00,0.00,0.22,0.00,0.04,0.00,0.00,19.38,0.00,0.00,0.00,0.00,0.00
GG,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.04,0.00,0.00,0.00,0.00,0.00
N64,6.58,0.00,0.22,13.35,7.05,2.19,129.95,0.00,0.00,10.71,1.01,0.00,1.98
NES,0.00,0.00,14.89,0.00,10.46,16.95,183.97,0.00,0.00,0.00,0.00,0.00,0.00
PC,47.58,2.60,0.82,71.44,0.63,2.10,0.00,11.64,0.00,3.13,12.41,0.00,15.18
PS,30.05,9.06,9.88,90.46,33.12,18.88,0.00,0.00,193.73,29.54,14.11,3.27,8.84
PS2,85.59,41.82,34.64,255.79,82.02,49.66,0.00,30.87,172.80,75.37,90.61,18.97,33.95
PS3,126.39,2.42,30.38,168.71,33.57,40.60,0.00,30.40,145.98,27.23,83.87,10.69,70.82
PS4,40.26,0.00,2.60,55.32,6.93,11.11,0.00,1.87,30.71,0.00,25.31,2.61,31.66
PSP,10.81,2.62,18.01,39.02,20.81,18.15,0.00,16.03,54.09,14.14,21.66,2.84,9.49
PSV,1.86,0.00,0.70,3.91,1.59,6.10,0.00,2.62,10.19,0.00,0.85,2.80,3.37
SAT,0.00,0.00,1.29,0.08,0.76,1.63,0.00,18.91,0.00,0.00,0.00,0.41,0.00
SCD,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.87,0.00,0.00,0.00,0.00,0.00
SNES,0.00,0.00,18.88,0.00,4.67,10.81,96.84,0.00,0.00,0.49,0.00,2.97,0.00
WS,0.00,0.00,0.00,0.00,0.00,0.66,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Wii,62.56,7.80,8.59,62.58,17.82,13.48,390.46,41.22,0.00,32.89,18.27,0.53,92.21
WiiU,4.15,0.00,0.26,1.28,0.00,1.84,57.90,1.28,0.00,0.16,0.14,0.12,5.78
X360,159.02,6.66,22.40,181.04,13.47,13.34,0.00,23.39,0.00,38.25,95.90,4.41,81.59
XB,32.79,7.65,1.37,58.33,4.74,2.53,0.00,9.83,0.00,9.86,12.05,0.93,23.36
XOne,23.55,0.00,0.35,29.34,1.26,2.46,0.00,0.50,0.00,0.00,13.00,0.29,17.91

In [28]:
#solve by merging so no platform x or y, and the index starts reset
#solve by filtering publishers <= 250 using value_counts and filtering df with list no group bys or joins
#df_filtered_two = df[['publisher']]
df_filtered_two = df['publisher'].value_counts()
df_filtered_two = df_filtered_two[df_filtered_two >= 250]
df_filtered_two = df[df['publisher'].isin(df_filtered_two.index)]
df_filtered_two = df_filtered_two[['publisher', 'platform', 'global_sales']].groupby(by = ['publisher', 'platform']).sum()
#df_filtered_two = df_filtered_two[['publisher', 'platform', 'global_sales']].groupby(by = ['publisher', 'platform']).sum()
df_filtered_two

                     global_sales
publisher  platform
Activision 2600             19.42
           3DS               4.66
           DC                0.10
           DS               42.11
           GB                1.33
...                           ...
Ubisoft    Wii              92.21
           WiiU              5.78
           X360             81.59
           XB               23.36
           XOne             17.91

[226 rows x 1 columns]

In [29]:
df_filtered_two.reset_index().pivot(columns = 'publisher', values = 'global_sales', index = 'platform').fillna(0)

publisher,Activision,Atari,Capcom,Electronic Arts,Konami Digital Entertainment,Namco Bandai Games,Nintendo,Sega,Sony Computer Entertainment,THQ,Take-Two Interactive,Tecmo Koei,Ubisoft
platform,,,,,,,,,,,,,
2600,19.42,50.09,0.00,0.00,0.00,0.00,0.00,0.40,0.00,0.00,0.00,0.00,0.00
3DO,0.00,0.00,0.00,0.00,0.06,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
3DS,4.66,0.05,10.68,2.72,2.31,11.37,156.45,5.84,0.00,0.52,0.15,0.67,4.31
DC,0.10,0.00,0.27,0.00,0.06,0.38,0.00,12.52,0.00,0.00,0.00,0.00,0.20
DS,42.11,7.13,9.45,32.95,13.52,16.06,349.75,29.54,0.00,36.68,9.46,1.94,59.71
GB,1.33,0.00,1.57,1.73,6.48,3.23,230.09,0.00,0.00,0.00,0.00,0.00,0.12
GBA,15.30,12.90,6.65,14.31,19.20,5.82,112.00,5.31,0.00,47.83,0.35,0.01,9.84
GC,13.35,6.42,6.77,27.96,3.07,4.74,79.15,9.53,0.00,13.97,0.39,0.09,4.40
GEN,0.00,0.00,0.22,0.00,0.04,0.00,0.00,19.38,0.00,0.00,0.00,0.00,0.00
GG,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.04,0.00,0.00,0.00,0.00,0.00
N64,6.58,0.00,0.22,13.35,7.05,2.19,129.95,0.00,0.00,10.71,1.01,0.00,1.98
NES,0.00,0.00,14.89,0.00,10.46,16.95,183.97,0.00,0.00,0.00,0.00,0.00,0.00
PC,47.58,2.60,0.82,71.44,0.63,2.10,0.00,11.64,0.00,3.13,12.41,0.00,15.18
PS,30.05,9.06,9.88,90.46,33.12,18.88,0.00,0.00,193.73,29.54,14.11,3.27,8.84
PS2,85.59,41.82,34.64,255.79,82.02,49.66,0.00,30.87,172.80,75.37,90.61,18.97,33.95
PS3,126.39,2.42,30.38,168.71,33.57,40.60,0.00,30.40,145.98,27.23,83.87,10.69,70.82
PS4,40.26,0.00,2.60,55.32,6.93,11.11,0.00,1.87,30.71,0.00,25.31,2.61,31.66
PSP,10.81,2.62,18.01,39.02,20.81,18.15,0.00,16.03,54.09,14.14,21.66,2.84,9.49
PSV,1.86,0.00,0.70,3.91,1.59,6.10,0.00,2.62,10.19,0.00,0.85,2.80,3.37
SAT,0.00,0.00,1.29,0.08,0.76,1.63,0.00,18.91,0.00,0.00,0.00,0.41,0.00
SCD,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.87,0.00,0.00,0.00,0.00,0.00
SNES,0.00,0.00,18.88,0.00,4.67,10.81,96.84,0.00,0.00,0.49,0.00,2.97,0.00
WS,0.00,0.00,0.00,0.00,0.00,0.66,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Wii,62.56,7.80,8.59,62.58,17.82,13.48,390.46,41.22,0.00,32.89,18.27,0.53,92.21
WiiU,4.15,0.00,0.26,1.28,0.00,1.84,57.90,1.28,0.00,0.16,0.14,0.12,5.78
X360,159.02,6.66,22.40,181.04,13.47,13.34,0.00,23.39,0.00,38.25,95.90,4.41,81.59
XB,32.79,7.65,1.37,58.33,4.74,2.53,0.00,9.83,0.00,9.86,12.05,0.93,23.36
XOne,23.55,0.00,0.35,29.34,1.26,2.46,0.00,0.50,0.00,0.00,13.00,0.29,17.91

In [30]:
l1 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
l1
for num in l1:
  #print(f'{num}\n')
  print(num)

0
1
2
3
4
5
6
7
8
9

In [31]:
l2 = ['one', 'two', 'three', 'four', 'five']
dick = {}
dick['l2'] = l2
dick['l1'] = l1[1:6]
dick

{'l2': ['one', 'two', 'three', 'four', 'five'], 'l1': [1, 2, 3, 4, 5]}

In [32]:
dick.keys()
dick.values()
#del(dick['l1'])
dick
dick.clear()
dick

{}

In [33]:
def no_name(funcNum = 1):
  return funcNum + 1

no_name(10)

11

In [34]:
def is_int(dick, dickKey, dickVal):
  if type(dickVal) == int:
    dick[dickKey] = dickVal
  return dick
dick = is_int(dick, 1, 1)
dick

{1: 1}

In [35]:
def contains(dick, l1, l2):
  for i in range(len(l2)):
    if l2[i] not in dick:
      dick[l2[i]] = l1[i]
  return dick
dick = contains(dick, l1, l2)
dick

{1: 1, 'one': 0, 'two': 1, 'three': 2, 'four': 3, 'five': 4}

In [36]:
steam = pd.read_csv('/content/gdrive/MyDrive/Teaching Notebooks/Data/Valve_Player_Data.csv')

In [37]:
steam = steam.drop('URL', axis = 1)
steam

,Month_Year,Avg_players,Gain,Percent_Gain,Peak_Players,Date,Game_Name
0,September 2021,512350.92,268.96,+0.05%,942519,2021-09-01,Counter Strike: Global Offensive
1,August 2021,512081.96,6014.60,+1.19%,802544,2021-08-01,Counter Strike: Global Offensive
2,July 2021,506067.36,-43279.72,-7.88%,763523,2021-07-01,Counter Strike: Global Offensive
3,June 2021,549347.08,-110541.81,-16.75%,929940,2021-06-01,Counter Strike: Global Offensive
4,May 2021,659888.89,-63457.63,-8.77%,1087197,2021-05-01,Counter Strike: Global Offensive
...,...,...,...,...,...,...,...
5266,December 2016,192.03,-21.90,-10.24%,405,2016-12-01,Divinity: Original Sin 2
5267,November 2016,213.92,-134.68,-38.63%,537,2016-11-01,Divinity: Original Sin 2
5268,October 2016,348.60,-201.75,-36.66%,1031,2016-10-01,Divinity: Original Sin 2
5269,September 2016,550.36,543.26,+7654.89%,2836,2016-09-01,Divinity: Original Sin 2
5270,August 2016,7.10,NaN,NaN,18,2016-08-01,Divinity: Original Sin 2

In [38]:
steam.columns = steam.columns.str.lower()
steam = steam.rename(columns={'gain':'change', 'percent_gain':'percent_change'})
#steam['percent_change'] = steam['percent_change'].fillna('0.00%')
steam['change'] = steam['change'].fillna('0.00')
steam['percent'] = steam['percent_change'].str.lstrip('+').str.rstrip('%').astype(float)#.map(lambda x: x.lstrip('+').rstrip('%')).astype(float)
steam['game_name'] = steam['game_name'].str.strip()
steam = steam[steam['date'] == '2021-09-01']
steam

,month_year,avg_players,change,percent_change,peak_players,date,game_name,percent
0,September 2021,512350.92,268.96,+0.05%,942519,2021-09-01,Counter Strike: Global Offensive,0.05
111,September 2021,391082.08,-33898.09,-7.98%,666838,2021-09-01,Dota 2,-7.98
222,September 2021,167102.12,-17726.28,-9.59%,400709,2021-09-01,PUBG: Battlegrounds,-9.59
277,September 2021,139647.96,-29880.22,-17.63%,273617,2021-09-01,Apex Legends,-17.63
288,September 2021,81854.01,6838.04,+9.12%,100830,2021-09-01,Team Fortress 2,9.12
...,...,...,...,...,...,...,...,...
5046,September 2021,5065.96,-7433.99,-59.47%,14949,2021-09-01,Battlefield 1,-59.47
5062,September 2021,5054.50,-1604.41,-24.09%,10527,2021-09-01,Dying Light,-24.09
5142,September 2021,6678.51,-856.87,-11.37%,9160,2021-09-01,Slay the Spire,-11.37
5193,September 2021,7693.27,-2750.38,-26.34%,12087,2021-09-01,The Sims 4,-26.34
5209,September 2021,10498.94,3042.81,+40.81%,19586,2021-09-01,Divinity: Original Sin 2,40.81

In [39]:
df_pc = df[df['platform'] == 'PC']
df_steam = pd.merge(left = steam, right = df, left_on = 'game_name', right_on = 'name', how = 'left')
latest_df_steam = df_steam
latest_df_steam = latest_df_steam.drop(['name', 'publisher_lower', 'publisher_count', 'publisher_whitespace', 'whitespace_count', 'split', 'split2', 'month_year'], axis = 1)
latest_df_steam['date'] = pd.to_datetime(latest_df_steam['date'], format = '%Y-%m-%d')
latest_df_steam['month'] = latest_df_steam['date'].dt.month
latest_df_steam['year'] = latest_df_steam['date'].dt.year
#latest_df_steam = latest_df_steam[(latest_df_steam['date'] == '2021-09-01') & (latest_df_steam['platform'] == 'PC')]
latest_df_steam
#would probably be better to filter to latest date before merging, but might want to use df_steam for something else
#might be a good idea to drop or combine the different platforms, since steam data is only PC potentially just drop all of the other platforms

,avg_players,change,percent_change,peak_players,date,game_name,percent,rank,platform,release_year,genre,publisher,na_sales,eu_sales,jp_sales,other_sales,global_sales,month,year
0,512350.92,268.96,+0.05%,942519,2021-09-01,Counter Strike: Global Offensive,0.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,2021
1,391082.08,-33898.09,-7.98%,666838,2021-09-01,Dota 2,-7.98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,2021
2,167102.12,-17726.28,-9.59%,400709,2021-09-01,PUBG: Battlegrounds,-9.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,2021
3,139647.96,-29880.22,-17.63%,273617,2021-09-01,Apex Legends,-17.63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,2021
4,81854.01,6838.04,+9.12%,100830,2021-09-01,Team Fortress 2,9.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,5054.50,-1604.41,-24.09%,10527,2021-09-01,Dying Light,-24.09,2556.0,XOne,2015.0,Action,Warner Bros. Interactive Entertainment,0.43,0.30,0.01,0.07,0.81,9,2021
117,5054.50,-1604.41,-24.09%,10527,2021-09-01,Dying Light,-24.09,8077.0,PC,2015.0,Action,Warner Bros. Interactive Entertainment,0.11,0.06,0.00,0.02,0.18,9,2021
118,6678.51,-856.87,-11.37%,9160,2021-09-01,Slay the Spire,-11.37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,2021
119,7693.27,-2750.38,-26.34%,12087,2021-09-01,The Sims 4,-26.34,479.0,PC,2014.0,Simulation,Electronic Arts,0.96,1.72,0.00,0.29,2.97,9,2021
120,10498.94,3042.81,+40.81%,19586,2021-09-01,Divinity: Original Sin 2,40.81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,2021

In [40]:
latest_df_steam.dtypes
#determine which rows are dropped after joining
#join and check lengths
#antijoin and see if there are rows
#unique values for the games, then compare list
#check lengths of both dfs
print(len(df[df['platform'] == 'PC']))
#print(df['release_year'].max())
print(len(steam))
#print(len(steam[steam['date'] == '2020-12-01'])) is 88 so 10 new games in 2021
#print(df[df['name'].str.contains('Team')].to_string())#df['platform'] == 'PC'].to_string())#latest_df_steam.to_string())
print(df_steam[df_steam['release_year'].isnull()].to_string())

960
98
         month_year  avg_players    change percent_change  peak_players        date                                    game_name  percent  rank name platform  release_year genre publisher  na_sales  eu_sales  jp_sales  other_sales  global_sales publisher_lower  publisher_count publisher_whitespace  whitespace_count split split2
0    September 2021    512350.92    268.96         +0.05%        942519  2021-09-01             Counter Strike: Global Offensive     0.05   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
1    September 2021    391082.08 -33898.09         -7.98%        666838  2021-09-01                                       Dota 2    -7.98   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
2    September 2021    167102.12 -17726.28         -9.59%        400709  2021-09-01                          PUBG: Battlegrounds    -9.59   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
3    September 2021    139647.96 -29880.22        -17.63%        273617  2021-09-01                                 Apex Legends   -17.63   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
4    September 2021     81854.01   6838.04         +9.12%        100830  2021-09-01                              Team Fortress 2     9.12   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
10   September 2021     64272.23   9104.06        +16.50%        160720  2021-09-01                           NARAKA: BLADEPOINT    16.50   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
11   September 2021     42727.96   -597.31         -1.38%         67845  2021-09-01                             Wallpaper Engine    -1.38   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
12   September 2021     69502.99 -13829.21        -16.60%        122359  2021-09-01                                         Rust   -16.60   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
13   September 2021     89845.19  32606.68        +56.97%        147513  2021-09-01                                    Destiny 2    56.97   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
14   September 2021     46968.35  -3785.16         -7.46%         82680  2021-09-01                                     Warframe    -7.46   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
15   September 2021     51913.56      0.00            NaN         67806  2021-09-01                               Cookie Clicker      NaN   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
16   September 2021     51139.69   1233.49         +2.47%        111554  2021-09-01               Tom Clancy's Rainbow Six Seige     2.47   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
17   September 2021     44196.05  -4492.35         -9.23%         73590  2021-09-01                        Football Manager 2021    -9.23   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
18   September 2021     29239.24   -574.96         -1.93%         45922  2021-09-01                                     PAYDAY 2    -1.93   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
19   September 2021     39489.46  -8058.66        -16.95%         66133  2021-09-01                        ARK: Survival Evolved   -16.95   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
20   September 2021     51390.73    262.68         +0.51%         82776  2021-09-01                             Dead by Daylight     0.51   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
21   September 2021     38634.11   7203.65        +22.92%         71565  2021-09-01                  Sid Meier's Civilization VI    22.92   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
22   September 2021     30876.43  19801.91       +178.81%         41962  2021-09-01                                         MIR4   178.81   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
23   September 2021     24874.39    -259.9         -1.03%         33682  2021-09-01                                     Unturned    -1.03   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
32   September 2021     25179.81    593.23         +2.41%         43439  2021-09-01                                  War Thunder     2.41   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
34   September 2021     27266.28  15721.84       +136.19%         89814  2021-09-01                                Battlefield V   136.19   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
35   September 2021     32988.16  15662.25        +90.40%        109793  2021-09-01                                      Valheim    90.40   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
36   September 2021     17285.80   1017.95         +6.26%         38695  2021-09-01                         World of Tanks Blitz     6.26   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
37   September 2021     20207.77  -1276.11         -5.94%         34974  2021-09-01                                         Dayz    -5.94   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
38   September 2021     18725.95  -3498.56        -15.74%         33222  2021-09-01                      Total War: WARHAMMER II   -15.74   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
39   September 2021     15029.51  -2837.58        -15.88%         33365  2021-09-01                        Don't Starve Together   -15.88   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
44   September 2021     21523.45  -5876.05        -21.45%         39242  2021-09-01                                  Garry's Mod   -21.45   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
45   September 2021     15486.47  -3537.55        -18.60%         31712  2021-09-01                        Monster Hunter: World   -18.60   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
46   September 2021     24320.88  -6246.22        -20.43%         36516  2021-09-01                               Stardew Valley   -20.43   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
47   September 2021     31514.52  -8787.06        -21.80%         52541  2021-09-01                     FINAL FANTASY XIV Online   -21.80   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
48   September 2021     19808.97 -20457.22        -50.80%         47966  2021-09-01                              Bless Unleashed   -50.80   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
52   September 2021      6926.76    993.44        +16.74%         22213  2021-09-01                            é›€é­‚éº»å°†(MahjongSoul)    16.74   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
53   September 2021     20348.73  -9109.17        -30.92%         31984  2021-09-01                                     RimWorld   -30.92   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
54   September 2021     14932.94   -992.85         -6.23%         28444  2021-09-01                        Red Dead Redemption 2    -6.23   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
57   September 2021     17256.39  -2010.41        -10.43%         24034  2021-09-01                                 Black Desert   -10.43   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
60   September 2021     17193.62   -1197.2         -6.51%         36865  2021-09-01                         Farming Simulator 19    -6.51   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
61   September 2021     19802.74  -2209.46        -10.04%         32075  2021-09-01  The Elder Scrolls V: Skyrim Special Edition   -10.04   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
68   September 2021      7745.29   -275.12         -3.43%         25039  2021-09-01                             Forza Horizion 4    -3.43   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
69   September 2021     14939.80  -1659.78        -10.00%         25799  2021-09-01                        Europa Universalis IV   -10.00   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
70   September 2021     14825.23  -1807.81        -10.87%         28043  2021-09-01                                     Spacewar   -10.87   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
71   September 2021     14502.18   -1313.4         -8.30%         23602  2021-09-01        Age of Empires II: Definitive Edition    -8.30   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
72   September 2021     24523.50      0.00            NaN         46563  2021-09-01               Pathfinder: Wrath of Righteous      NaN   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
73   September 2021      8630.43  -1430.13        -14.22%         21377  2021-09-01                         Yu-Gi-Oh! Duel Links   -14.22   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
74   September 2021     13114.44  -2507.32        -16.05%         19815  2021-09-01                The Binding of Isaac: Rebirth   -16.05   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
75   September 2021     12071.63     23.66         +0.20%         22321  2021-09-01                                         SCUM     0.20   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
79   September 2021     12119.79    1296.6        +11.98%         21906  2021-09-01                                     Factorio    11.98   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
80   September 2021     11981.34  -1747.76        -12.73%         20493  2021-09-01                 Mount & Blade II: Bannerlord   -12.73   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
81   September 2021     11068.81  -2524.27        -18.57%         18529  2021-09-01                                   tModLoader   -18.57   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
82   September 2021     11514.10      0.00            NaN         20325  2021-09-01                                     NBA 2k22      NaN   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
83   September 2021     19383.82   5103.96        +35.74%         38111  2021-09-01                                  Bloons TD 6    35.74   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
84   September 2021     16329.35   -398.91         -2.38%         26521  2021-09-01                                   Brawlhalla    -2.38   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
85   September 2021     15274.20  -1079.31         -6.60%         26175  2021-09-01                                       VRChat    -6.60   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
86   September 2021     10915.20    300.42         +2.83%         27277  2021-09-01                 Fall Guys: Ultimate Knockout     2.83   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
87   September 2021     12649.78   -266.44         -2.06%         25623  2021-09-01                                       Arma 3    -2.06   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
88   September 2021      9093.16   -800.28         -8.09%         14283  2021-09-01                        Football Manager 2020    -8.09   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
89   September 2021      7289.85   -244.49         -3.25%         14757  2021-09-01                            World of Warships    -3.25   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
90   September 2021     14687.51  -4635.98        -23.99%         27338  2021-09-01                            EA SPORTS FIFA 21   -23.99   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
91   September 2021      9169.27  -1915.61        -17.28%         14879  2021-09-01                               DARK SOULS III   -17.28   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN
92   September 2021      9982.46  -1062.04         -9.62%         17674  2021-09-01                           Crusader Kings III    -9.62   NaN  NaN      NaN           NaN   NaN       NaN       NaN       NaN       NaN          NaN           NaN             NaN              NaN                  NaN               NaN   NaN    NaN

In [41]:
steam.describe()
steam.value_counts()
df[df['name'].str.contains('Rainbow Six: Siege')]
#free games and mispellings/changes in format
#df['release']
#check what max year is for release year in df, then see how many games released after that in the steam dataset
#business analysts, i am gamer dev, what kind of game do I want to fund next, and what we should be expecting, genres, how many players are staying
#make questions and figure out ways to investigate

,rank,name,platform,release_year,genre,publisher,na_sales,eu_sales,jp_sales,other_sales,global_sales,publisher_lower,publisher_count,publisher_whitespace,whitespace_count,split,split2
758,760,Tom Clancy's Rainbow Six: Siege,PS4,2015.0,Shooter,Ubisoft,0.54,1.16,0.13,0.32,2.15,ubisoft,7.0,Ubisoft,7.0,Tom,Clancy's Rainbow Six: Siege
1531,1533,Tom Clancy's Rainbow Six: Siege,XOne,2015.0,Shooter,Ubisoft,0.73,0.44,0.00,0.12,1.29,ubisoft,7.0,Ubisoft,7.0,Tom,Clancy's Rainbow Six: Siege
7211,7213,Tom Clancy's Rainbow Six: Siege,PC,2015.0,Shooter,Ubisoft,0.12,0.08,0.00,0.02,0.22,ubisoft,7.0,Ubisoft,7.0,Tom,Clancy's Rainbow Six: Siege